# This is a sample configuration that can be used to easily get the gateway docker compose deployment feature
# running for a local setup as part of software development. It is not needed for deployments on a server.

ygg:
  admin:
    gitService:
      url: https://bitbucket.org/perezdf/anthill-settings.git
      user: fpd.judo@gmail.com
      password: fpdvip1234
    gettingStarted:
      consumer:
        testService:
          provider.username: tutorial-service-provider-github-username
          uriIdentifier: humidity-by-locations
    database:
      insertSampleDataOnStartup: true
      sampleDataUsername: api-provider-github-username
      sampleDataUsernameApiConsumer: api-consumer-github-username

    api-base-url-for-gateway: http://host.docker.internal:8080/api/
  proxy:
    executable-jar:
     template.url: file:///C:/Users/baier.ATB/Documents/Workspace/ATB/coatrack/spring-boot/proxy/target/coatrack-proxy-
    generate-bootstrap-properties:
      spring.cloud.config.uri: http://host.docker.internal:8998

spring.cloud.config.uri: http://localhost:8998