apiVersion: v1
kind: ConfigMap
metadata:
  name: coatrack-config
  namespace: coatrack
data:
  spring.profiles.active: dev
  spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: "true"
  spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  logging.level: INFO
  logging.level.org: INFO
  logging.level.org.springframework: INFO
  logging.level.org.springframework.security: INFO
  logging.level.eu.coatrack: DEBUG
  ygg.mail.sender.user: "" 
  ygg.mail.sender.password: ""
  ygg.mail.server.url: ""
  ygg.mail.server.port: "0"
  spring.cloud.config.uri: http://coatrack-config
