apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
     app.kubernetes.io/name: coatrack-admin
  name: coatrack-admin
  namespace: coatrack
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: coatrack-admin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: coatrack-admin
    spec:
      containers:
        - name: coatrack-admin-container
          image: coatrack/coatrack-admin:2.0.0-SNAPSHOT
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: coatrack-config
          env:
            - name: server.port
              value: '80'
          ports:
            - containerPort: 80
          volumeMounts:
            - name: gluster
              mountPath: /mnt/coatrack
              readOnly: false
      volumes:
        - name: gluster
          persistentVolumeClaim:
            claimName: coatrack-pvc
      imagePullSecrets:
      - name: docker-login
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: coatrack-config-server
  name: coatrack-config-server
  namespace: coatrack
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: coatrack-config-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: coatrack-config-server
    spec:
      containers:
        - name: coatrack-config-server-container
          image: coatrack/coatrack-config-server:2.0.0-SNAPSHOT
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: coatrack-config
          env:
            - name: server.port
              value: '80'
          ports:
            - containerPort: 80
          volumeMounts:
            - name: gluster
              mountPath: /mnt/coatrack
              readOnly: false
      volumes:
        - name: gluster
          persistentVolumeClaim:
            claimName: coatrack-pvc
      imagePullSecrets:
        - name: docker-login
