ribbon.eureka.enabled: false
spring.metrics.servo.enabled: false

# default port for testing
# Please note: when creating a gateway via admin GUI, this port can be configured
server.port: 8088

# unique ID of this gateway
# Please note: in production setting this test ID will be superseded/replaced via the individually generated gateway config
proxy-id: aa11aa22-aa33-aa44-aa55-aa66aa77aa88

# parameters related to the communication with CoatRack admin
ygg.admin:
  # Please note: in production setting this URL will be superseded by the one from ygg-admin config, which is put into the individual gateway config
  api-base-url: http://localhost:8080/api/
  resources:
    proxies: proxies
    metrics: metrics
    metricsTransmission: metricsTransmission
    api-keys: api-keys
    search-api-keys-by-token-value: api-keys/search/findByKeyValue?keyValue=
    get-api-key-list-by-gatewayId: gateways/api-keys

custom-metrics:
  prefix.counter: CUSTOM.

# The following gateway routes are just for local development testing purposes
zuul:
  routes:
    # service IDs in line with admin's DatabaseInitializer
    weather-service.url: https://example.org/
    humidity-by-location.url: http://example.org/

logging:
  level:
    eu.coatrack.proxy: DEBUG
    org.springframework.security: DEBUG

# The gateway has the ability to work even if the CoatRack admin server is not reachable. If admin is not reachable
# for longer than this period of time, the gateway will reject all service API requests until a connection could
# be re-established.
number-of-minutes-the-gateway-shall-work-in-offline-mode: 60

# The gateway periodically updates its local API key list which is used for authorization of incoming service
# requests if the connection to the CoatRack admin server does not work. This is the time interval for these
# updates in milliseconds.
local-api-key-list-update-interval-in-millis: 300_000